In [29]:
#  basic concept of inheritance

# parent class
class Animal:      
    def __init__(self, name='animal', age=0):
        self.name = name
        self.age = age

# child class        
class Canine(Animal):
#     def __init__(self, name='bird', age=5, fur_colour = 'brown'):
#         self.fur_colour = fur_colour
#         Animal.__init__(self)
#         super().__init__()      # automatically pass in the child object to the parent constructor
#         super().__init__(name, age)  
#         super().__init__(self)   # assign the child object to the argument 'name'
        
        print('name is:', self.name)
        print('age is:', self.age)
    


NameError: name 'self' is not defined

In [28]:
aa = Canine()

name is: <__main__.Canine object at 0x0000020E2158D8B0>
age is: 0


In [16]:
# single inheritance

class A:
    def __init__(self, n=0, k=0):
        self.n = n
        self.k = k

    def add(self, m):
        print('self is {0} @A.add'.format(self))
        self.n += m    # B.n


class B(A):
    def __init__(self, n, k=15):   # override the constructor __init__()
        super().__init__(n, k)
        print('the value of attribute n is:', self.n)
        print('the value of attribute k is:', self.k)

    def add(self, m):
        print('self is {0} @B.add'.format(self))
        super().add(m)
        self.n += 3

In [17]:
a = A()
b = B(3)
b.add(2)
print(b.n)

the value of attribute n is: 3
the value of attribute k is: 15
self is <__main__.B object at 0x0000020E1FEA56A0> @B.add
self is <__main__.B object at 0x0000020E1FEA56A0> @A.add
8


In [18]:
# use parent class name to call __init__


class GrandParent:
    def __init__(self, name):  
        print('Grandparent init begins')
        self.name = name
        print('Grandparent init ends')
        
class Parent1(GrandParent):
    def __init__(self, name, age):  
        print('Parent1 init begins')
        self.age = age
        GrandParent.__init__(self, name)
        print('Parent1 init ends')
        
class Parent2(GrandParent):
    def __init__(self, name, gender): 
        print('Parent2 init begins')
        self.gender = gender
        GrandParent.__init__(self, name)
        print('Parent2 init ends')
        
        
class Son(Parent1, Parent2):
    def __init__(self, name, age, gender): 
        print('son init begins')
        Parent1.__init__(self, name, age)  
        Parent2.__init__(self, name, gender)
        print('son init ends')        
        

In [19]:
sonson = Son('abcd', 20, 'unknown')
print('name is:', sonson.name)
print('name is:', sonson.age)
print('name is:', sonson.gender)

son init begins
Parent1 init begins
Grandparent init begins
Grandparent init ends
Parent1 init ends
Parent2 init begins
Grandparent init begins
Grandparent init ends
Parent2 init ends
son init ends
name is: abcd
name is: 20
name is: unknown


In [29]:
#  use super() to call __init__


class GrandParent:
    def __init__(self, name, *args, **kwargs):  # accept variable length arguments
        print('Grandparent init begins')
        self.name = name
        print('Grandparent init ends')
        
class Parent1(GrandParent):
    def __init__(self, name, age, *args, **kwargs):  # accept variable length arguments
        print('Parent1 init begins')
        self.age = age
        super().__init__(name, *args, **kwargs)
        print('Parent1 init ends')
        
class Parent2(GrandParent):
    def __init__(self, name, gender, *args, **kwargs):  # accept variable length arguments
        print('Parent2 init begins')
        self.gender = gender
        super().__init__(name, *args, **kwargs)
        print('Parent2 init ends')
        
        
class Son(Parent1, Parent2):
    def __init__(self, name, age, gender): 
        print('son init begins')
        super().__init__(name, age, gender)    # call the __init__ from both Parent1 and Parent2, in order
        print('son init ends')        
        

In [30]:
sonson = Son('abcd', 20, 'unknown')
print('name is:', sonson.name)
print('name is:', sonson.age)
print('name is:', sonson.gender)

son init begins
Parent1 init begins
Parent2 init begins
Grandparent init begins
Grandparent init ends
Parent2 init ends
Parent1 init ends
son init ends
name is: abcd
name is: 20
name is: unknown


In [7]:
# define some methods in multiple inheritance

class A:   
    def __init__(self):
        self.n = 4

    def add(self, m):  # fourth step
        print('self is {0} @A.add'.format(self))   #self == d, self.n == d.n == 5
        self.n += m    # d.n = 7


class B(A):
    
    def __init__(self, n, k=15):   
        super().__init__(n, k)

    def add(self, m):   # second step
        print('self is {0} @B.add'.format(self))   #self == d, self.n == d.n == 5
        super().add(m)  # search add method from [C,A]
        self.n += 3    # sixth step d.n = 14


class C(A):
    def __init__(self):
        self.n = 4

    def add(self, m):   # third step
        print('self is {0} @C.add'.format(self))   #self == d, self.n == d.n == 5
        super().add(m)  #  search add method from [A]
        self.n += 4     # fifth step d.n = 11


class D(B, C):
    def __init__(self):
        self.n = 5

    def add(self, m):   # first step
        print('self is {0} @D.add'.format(self))
        super().add(m)  # super() is a class! Search add method from [B,C,A]
        self.n += 5     # last step d.n = 19

In [8]:
d = D()
d.add(2)
print(d.n)

self is <__main__.D object at 0x7fa20152d670> @D.add
self is <__main__.D object at 0x7fa20152d670> @B.add
self is <__main__.D object at 0x7fa20152d670> @C.add
self is <__main__.D object at 0x7fa20152d670> @A.add
19


In [20]:
# the execution process
class D(B, C):          class B(A):            class C(A):             class A:
    def add(self, m):       def add(self, m):      def add(self, m):       def add(self, m):
        super().add(m)  1.--->  super().add(m) 2.--->  super().add(m)  3.--->  self.n += m
        self.n += 5   <------6. self.n += 3    <----5. self.n += 4     <----4. <--|
        (14+5=19)               (11+3=14)              (7+4=11)                (5+2=7)

SyntaxError: invalid syntax (<ipython-input-20-38b9fd648bb7>, line 2)

In [35]:
# linked list

class Node: 
    def __init__(self, value = None, next_address = None):
        self.value = value
        self.next = next_address  # to store the address of the next node
        
    def __str__(self):    # override the print function
        return str(self.value)   


In [36]:
# create the list

node1 = Node(1)
node2 = Node(2)
node3 = Node(3)
node1.next = node2    # node1 points to node2
node2.next = node3

In [38]:
# define the print list function

def printList(node):
    while node:
        print(node)
        node = node.next

In [39]:
printList(node1)

1
2
3


In [4]:
# array

# define a 1-dimentional array
import numpy as np

array_1 = np.array([1,2,3,4,5])
list_1 = [1,2,3,4,5]
print(array_1)
print(list_1)


[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [5]:
# create a 2-D array and list

array_2 = np.arange(6).reshape(2,3)
list_2 = [[0,1,2],[3,4,5]]

print(array_2)
print(list_2)

[[0 1 2]
 [3 4 5]]
[[0, 1, 2], [3, 4, 5]]


In [11]:
# get the value at the 1st row, 3rd column
print(array_2[0,2])
print(list_2[0][2])

# get the elements of the 3rd column 
print(list(array_2[0:,2]))    
print([list_2[0][2],list_2[1][2]])

2
2
[2, 5]
[2, 5]
